---
title: "抗癌戰友會 PO文 初步分析"
author: "r05741051_黃羽均"
date: "2017年9月3日"
output: html_document
---

發文次數分析
```{r}
library(dplyr)
library(lubridate)
library(plyr)

## read data
test<-read.csv("post.csv", stringsAsFactors=FALSE)

## 分析發文次數
post = as.data.frame(table(test$author,dnn = "author"))
post<-arrange(post,Freq,decreasing=T)
count_table=as.data.frame(table(table(test$author,dnn = "author")))

print(count_table)

##畫圖
hist(post$Freq,
     breaks = c(1:max(post[,2])),
     main = "Histogram of post",
     xlab = "Frequency in about 5 month")
```

PO文最多次
```{r}
head(post,10)
```
(按讚數不知道為什麼最大都是25)


多次PO文者 PO文時間差
```{r}

##資料加入po文頻率
test1 = left_join(test, post, by ="author")
##原資料剔除只po一次
test2=subset(test1, test1$Freq>=2)

#挑出要分析的欄
test3<-test2[ ,c(2,6) ]


#轉換時間格式
test3$update_time<-as.Date(as.POSIXlt(test3$update_time))

#求各作者po文時間差
test4<-as.data.frame(tapply(test3$update_time,
        test3$author,
       diff.difftime,unit="days"))

colnames(test4)<-c("difftime")

print(test4)

test5<-unlist(test4$difftime)
print(mean(test5))

```

